# Generated by Django 5.2.1 on 2025-05-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='click',
            field=models.IntegerField(default=0),
        ),
    ]
