# Generated by Django 5.2.1 on 2025-05-31 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_alter_campaigns_options_campaigns_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaigns",
            old_name="user",
            new_name="poster",
        ),
    ]
