# Generated by Django 5.2.1 on 2025-05-31 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0005_rename_user_campaigns_poster"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaigns",
            name="poster",
        ),
    ]
